version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/KOSASIH/Ceemot"
  dependencies_vendored = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  bootstrap_files = ["Ceemot"]

[[analyzers]]
name = "rust"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "16"

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["Ceemot"]

[[transformers]]
name = "google-java-format"
enabled = true

[[transformers]]
name = "rubocop"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "scalafmt"
enabled = true